KS-5-3 the solution of the problem
alexandrsemc/KotlinS pull request #16
Opened 2023-10-08 17:31 UTC by alexandrsemc

2023-10-09 16:57 UTC, ievetrov requested changes

2023-10-09 16:57 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    val yourNumber1 = readln()!!.toInt()
!! лишнее (отписал ранее)

2023-10-09 16:57 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    else if ( (yourNumber1 == SUPER_NUMBER1 && yourNumber2 != SUPER_NUMBER2) || (yourNumber1 == SUPER_NUMBER2 && yourNumber2 != SUPER_NUMBER1))
тут достаточно перечислить через ИЛИ только равенство первого или второго числа (не используя `!=`). этого будет достаточно

2023-10-09 16:57 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    println("Победные числа: 7 и 21")
числа стоит переиспользовать из переменных, чтобы не было хардкода

2023-10-09 19:15 UTC, alexandrsemc commented
Забыл поменять 5-2 на 5-3 в Kommit., (сам не рад).

2023-10-10 13:39 UTC, ievetrov requested changes

2023-10-10 13:39 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    else if ( yourNumber1 == SUPER_NUMBER1  || yourNumber2 == SUPER_NUMBER2 )
не хватает сравнения 1 чиста со вторым выйгрышным - это тоже считается (ввод в другом порядке)

2023-10-11 16:36 UTC, ievetrov approved these changes

2023-10-11 18:53 UTC, merged