Lesson5 task1
alexandrsemc/KotlinS pull request #19
Opened 2023-10-08 18:41 UTC by alexandrsemc

2023-10-08 18:45 UTC, alexandrsemc commented
Здесь я вновь по своему невниманию, как-то криво, но выложил задачу...

2023-10-09 17:02 UTC, ievetrov requested changes

2023-10-09 17:02 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_5.kt
> +fun main(){
да, вот тут лишняя задача залетела в пулл реквест с задачей 5-1

2023-10-09 17:02 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    val task  = "1 + 6"
Нам необходимо думать об обслуживании и расширяемости кода. Сумма должна считаться автоматически из объявленных заранее переменных.

сначала давай объявим переменные, затем создадим строку, в которой будут они использоваться

2023-10-09 17:02 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    val result = if( solution == 7) "Добро пожаловать!"
Значение в этом коде является [магическим числом](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)
не лучшая практика. добавь, пожалуйста, переменные для инициализированных значений и суммы)

2023-10-09 17:02 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    val solution = readln()!!.toInt()
!!

2023-10-10 13:42 UTC, ievetrov requested changes
по задаче ок, но по гит-флоу отписал. если что пингуй в лс

2023-10-10 13:42 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_5.kt
> +fun main(){
задачу надо удалить из этой ветки) все как обсуждали раньше)
если вдруг забылось, могу продублировать в лс, чтобы наверняка

2023-10-12 11:54 UTC, ievetrov approved these changes

2023-10-12 19:22 UTC, merged