KS-6-1 the solution of the problem
alexandrsemc/KotlinS pull request #20
Opened 2023-10-08 18:57 UTC by alexandrsemc

2023-10-09 21:24 UTC, alexandrsemc commented
Вчера отправил, сегодня посмотрел и увидел что не правильно решил, пока не разобрался с решением.

2023-10-11 16:40 UTC, ievetrov requested changes

2023-10-11 16:40 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_1.kt
> +    val login = readln().toString()
приведение к строке `.toString()` излишнее действие, потому что под капотом метод чтения с консоли и так переводит все входные данные в строку

2023-10-11 16:40 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_1.kt
> +    }while (counter >0)
это получается бесконечный счетчик будет?) ну либо программа упадет, когда из-за переполнения памяти.

если хочется сделать бесконечный цикл можно использовать while(true), но обращай внимание в каком условии надо прописать выход из цикла. он все еще бесконечный

2023-10-12 11:55 UTC, ievetrov approved these changes
отлично!

2023-10-12 19:23 UTC, merged