KS-6-2 the solution of the problem
alexandrsemc/KotlinS pull request #21
Opened 2023-10-09 21:20 UTC by alexandrsemc

2023-10-10 13:55 UTC, ievetrov requested changes

2023-10-10 13:55 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_2.kt
> +    while (numberOfSeconds > 0) {
По условию вроде не нужно делать цикл. Может можно обойтись одним вызовом sleep?)

2023-10-10 21:46 UTC, alexandrsemc commented
Я реально стараюсь, но к большому сожалению, пока мой мозг выдает те решения которые я отправляю...учусь).

2023-10-11 16:41 UTC, ievetrov commented
> Я реально стараюсь, но к большому сожалению, пока мой мозг выдает те решения которые я отправляю...учусь).

и получается великолепно! это распространенные ошибки, только через них происходит прогресс) темп отличный!

2023-10-11 16:42 UTC, ievetrov requested changes

2023-10-11 16:42 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_2.kt
> +    val time = numberOfSeconds*millisecond
напоминаю, арифметические знаки обосабливаются пробелами. рекомендую применять автоформатирование перед коммитом

2023-10-12 11:56 UTC, ievetrov requested changes

2023-10-12 11:56 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_2.kt
> +    val time = numberOfSeconds*millisecond
комментарий оставляется к конкретной строке (в данном случае 8).
здесь знак умножения надо обособить пробелами)

2023-10-12 19:31 UTC, alexandrsemc commented
Да, постараюсь быть внимательнее.

2023-10-13 13:47 UTC, ievetrov approved these changes
отлично!

2023-10-13 13:53 UTC, merged