Lesson8 task1
alexandrsemc/KotlinS pull request #28
Opened 2023-10-13 22:18 UTC by alexandrsemc

2023-10-14 12:57 UTC, ievetrov requested changes

2023-10-14 12:57 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_1.kt
> +    val day1 = readln().toInt()
все хорошо, но предлагаю тогда инициализировать массив в цикле, чтобы выглядело аккуратнее

2023-10-14 21:06 UTC, alexandrsemc commented
Нашел ошибку, пришлось переделать...надеюсь правильно.)

2023-10-15 09:13 UTC, ievetrov requested changes

2023-10-15 09:13 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_1.kt
> +    val day1 = readln().toInt()
я вроде оставил комментарий к 6 строке, но тут изменений нет)
давай проинициализируем все дни в цикле. 
чтобы на каждой итерации вызывать readln

2023-10-15 09:13 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_1.kt
> +    val viewsPerWeek = intArrayOf(day1, day2, day3, day4, day5, day6, day7)
например.
```
val viewsPerWeek = IntArray(7)

for (i in 0 until 7) {
    println("Введите просмотры для дня ${i + 1}:")
    viewsPerWeek[i] = read.....
}
```

2023-10-17 08:02 UTC, ievetrov approved these changes
ок!

2023-10-17 11:04 UTC, merged