KS-9-4 the solution of the problem
alexandrsemc/KotlinS pull request #37
Opened 2023-10-19 02:25 UTC by alexandrsemc

Застрял: sort() не работает...не до думал или не понял условие...

2023-10-19 21:40 UTC, alexandrsemc commented
Попытался еще раз.

2023-10-20 11:15 UTC, ievetrov requested changes

2023-10-20 11:15 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_4.kt
> +    val userIngredients = "olives, cucumbers, potato, leek, water"
сейчас эта переменная не используется. плюс в задании сказано что пользователь должен сам ввести ингредиенты в одну строку через запятую, давай немного доработаем.

для разделения полученной строки в список ингредиентов можно использовать функцию `split`)

2023-10-21 07:25 UTC, ievetrov approved these changes

2023-10-21 07:26 UTC, merged