KS-10-3 the solution of the problem
alexandrsemc/KotlinS pull request #40
Opened 2023-10-23 20:22 UTC by alexandrsemc

2023-10-24 14:07 UTC, ievetrov requested changes

2023-10-24 14:07 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_3.kt
> +    val symbols = ('0'..'9') + listOf('!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/', ' ')
Обрати внимание. Можно представить эту последовательность символов в виде [диапазона](https://ru.wikipedia.org/wiki/ASCII)

2023-10-24 14:07 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_3.kt
> +fun passwordGeneration(length: Int): String {
напоминаю, функции называем в инфинитиве

2023-10-24 14:07 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_3.kt
> +        .map { symbols.random() }
согласно ТЗ символы должны чередоваться с числами

2023-10-25 13:08 UTC, ievetrov requested changes

2023-10-25 13:08 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_3.kt
> +    println(toGeneratePassword(length))
да, ок, но вроде to не обязательно. для читаемости достаточно generate.. итд

2023-10-25 13:08 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_3.kt
> +    val symbols = listOf(
не совсем. вот еще более подробная таблица аски https://www.industrialnets.ru/files/misc/ascii.pdf

я предлагаю создать два диапазона - числовой и символьный.

чистовой у тебя уже был в предыдущем коммите, а символьный можно создать абсолютно такой же. тольео вместо чисел - спецсимволы

2023-10-26 19:44 UTC, alexandrsemc commented
То есть, если поменять val symbols = (' '..'9') вместо val symbols = ('0'..'9') + (' '..'/'). Тоже будет верно, правильно?

2023-10-27 18:41 UTC, ievetrov commented
> То есть, если поменять val symbols = (' '..'9') вместо val symbols = ('0'..'9') + (' '..'/'). Тоже будет верно, правильно?

конечно, они все в одной последовательности символов (символов - поэтому одинарные кавычки).
кроме того ты можешь сам поэксперементировать - вывести в консоль или воспользоваться дебагом в Идее и смотреть какая там полная строка на выбранной точке выполнения программы.

2023-10-27 18:44 UTC, ievetrov requested changes

2023-10-27 18:44 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_3.kt
> +        .map { symbols.random() }
этот комментарий не исправлен)
в конечной строке должны чередоваться символ/число и так далее.

сейчас у тебя один общий диапазон из всех чисел, но корректнее будет сделать 2 отдельных диапазона. и в цикле конкатенировать в строку эти символы поочередно. 
типа того pass += intRange.random() и далее также для символа.

2023-10-29 07:02 UTC, ievetrov requested changes

2023-10-29 07:02 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_3.kt
> +        print(result1)
все ок, только давай полученный результат не выводить, а записывать в строку, которую мы сможем вернуть из функции

сейчас ты из этой функции возвращаешь длину пароля, которую мы получили на вход, а нужно возвращать сгенерированный пароль

2023-10-29 07:02 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_3.kt
> +    while (n <= length / 2) {
как нам быть если придет число которое не делится на 2 без остатка? в случае длины пароля 7 у тебя будет результат 6 символов

попробуй итерироваться по всей длине пароля, а внутри цикла определять четная ли сейчас операция и в зависимости от этого добавлять к строке нужный символ

2023-11-19 10:29 UTC, alexandrsemc commented
Интернет дома "отвалился" когда "пушил" задачу, пока разбирался в проблеме, случайно отправил два "коммита"...)

2023-11-19 15:21 UTC, ievetrov approved these changes
отлично, все аккуратно

2023-11-20 15:37 UTC, merged