KS-10-2 the solution of the problem
alexandrsemc/KotlinS pull request #41
Opened 2023-10-24 22:16 UTC by alexandrsemc

2023-10-24 22:20 UTC, alexandrsemc commented
Скорее всего неправильно. Не могу пока догадаться как сделать валидацию данных отдельно...

2023-10-25 13:11 UTC, ievetrov requested changes

2023-10-25 13:11 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +    getLength()
для начала всю логику надо вернуть в мейн и выносить только валидацию длины пароля.

лучшей практикой будет расценить это требование буквально. то есть только валидировать и отдавать результат типа Boolean. для этого на вход в метод валидации надо передавать строку (которая будет логином или паролем)

2023-10-25 13:11 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +    val result = if (login >= minCharacterLength && password
и затем эту самую функцию вызывать прям в этом условии

2023-10-26 18:01 UTC, alexandrsemc commented
Что-то сделал...

2023-10-27 18:36 UTC, ievetrov requested changes

2023-10-27 18:36 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +    val result = if (getLength(login) && getLength(password)
все работает верно!
но оформлено не очень красиво. можно в принципе вообще не сохранять строку в result, а просто создать условие if и в нем вызывать принты в зависимости от условий.

но в текущей ситуации будет выглядеть симпатичнее вот так
<img width="324" alt="image" src="https://github.com/alexandrsemc/KotlinS/assets/34489023/b35c20d7-0c5e-4e1c-9453-eaebc0f2328b">

2023-10-27 18:36 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +fun getLength(a: String): Boolean {
предлагаю чуть точнее дать название. получить длину - это не то, что делает функция. она валидирует длину

2023-10-29 07:04 UTC, ievetrov requested changes

2023-10-29 07:04 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +    return a.length >= 4
Давай вынесем 4 в константу, чтобы не использовать магическое число

2023-10-30 22:32 UTC, ievetrov approved these changes

2023-10-30 22:33 UTC, merged