KS-11-3 the solution of the problem
alexandrsemc/KotlinS pull request #45
Opened 2023-11-03 17:16 UTC by alexandrsemc

2023-11-03 18:18 UTC, ievetrov requested changes

2023-11-03 18:18 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +    val listOfParticipants: MutableList<String>,
В целом все ок, но мы предполагаем по ТЗ, что пользователи - это часть сущности комнаты. Давай сделаем класс, например, Member и тут будет соответствующее поле со списком. Тип списка будет как раз новый класс пользователя. Для сущности “пользователь” также следует продумать (или частично перенести из этого  класса) его собственный набор полей.

2023-11-03 18:18 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +class Rooms(
Класс в данном контексте - это описание будущего конкретного экземпляра. Мы описываем сущность одной комнаты. Поэтому множественное название будет уместно разве что для списка комнат, но не для одного конкретного экземпляра.

2023-11-04 05:14 UTC, alexandrsemc commented
Искренне извиняюсь за свои попытки, писать хоть какой-то код, не все понимаю. Видео смотришь, вроде бы все понятно, а как доходит до задач, то после просмотра своего написанного кода - "кровь из глаз". У вас ,я понимаю, такая же реакция на мой код...)

2023-11-05 15:13 UTC, ievetrov commented
> Искренне извиняюсь за свои попытки, писать хоть какой-то код, не все понимаю. Видео смотришь, вроде бы все понятно, а как доходит до задач, то после просмотра своего написанного кода - "кровь из глаз". У вас ,я понимаю, такая же реакция на мой код...)

вновь отвечу, что это норма) это и есть процесс обучения. сколько бы не разжевывался материал в видео, когда самостоятельно делаешь - совсем другие ощущения))

прогресс очевиден, вспоминайте себя периодически месяц назад. уже знаете гораздо больше, качество кода растет от урока к уроку!

2023-11-05 15:22 UTC, ievetrov requested changes

2023-11-05 15:22 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +class Room(
Не совсем то, что я имел в виду. 

Member или User - неважно. Суть в том, чтобы создать вспомогательную сущность для пользователей. Но одной будет достаточно

2023-11-05 15:22 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +class Room(
далее listOfParticipants следует вернуть в поле класса комнаты. у комнаты есть список участников - тут все верно. но список должен быть параметризирован типом пользователь. это должен быть список объектов

`val listOfParticipants: MutableList<User>,
`

2023-11-05 15:22 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +    val speakerStatus: List<String>,
это тоже мне кажется больше относится к сущности пользователь

2023-11-06 15:30 UTC, ievetrov approved these changes
отлично, все верно. если вдруг путаница осталась почему так сделали, пингуй в ЛС)

2023-11-06 18:54 UTC, merged