KS-11-4 the solution of the problem
alexandrsemc/KotlinS pull request #46
Opened 2023-11-06 05:30 UTC by alexandrsemc

2023-11-07 06:44 UTC, ievetrov requested changes

2023-11-07 06:44 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_4.kt
> +class FavoritesTop(
для избранных блюд нам не обязательно создавать отдельный класс, можно просто добавить булеан поле `isFavorite` в `Dish`

2023-11-07 06:44 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_4.kt
> +class Dish(
блюда у нас также делятся на категории, давай сделаем класс для них и внутри каждой из категорий будет лежать список Dish

2023-11-08 16:32 UTC, ievetrov requested changes

2023-11-08 16:32 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_4.kt
> +class Button(
Кнопки давай вообще уберем, чтобы не отвлекали внимание. Это стандартные компоненты и отдельные кастомные классы делать для них не придется. 

Наша задача как архитектора - спроектировать классы для хранения данных, а не элементов UI.

2023-11-08 16:32 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_4.kt
> +    val category: Dish,
Тут класс назван верно.
Категория рецепта хранит 
- название категории
- ссылку на картинку
- список рецептов (или блюд)

2023-11-08 16:32 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_4.kt
> +    val category: Dish,
Для последнего нужно описать именно список объектов Dish. То есть listOf()

2023-11-08 16:32 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_4.kt
> +class Dish(
Для класса с блюдом будут такие поля
- название блюда
- ссылка на картинку
- Ингредиенты (тут внимательнее - это список новых объектов с типом "Ингредиент")

2023-11-09 18:17 UTC, ievetrov requested changes

2023-11-09 18:17 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_4.kt
> +    val listOfDish: List<String>,
Важный момент. Тут мы уже учимся работать с объектами. То есть включаем ООПшное мышление) Когда я сказал что тут будет список объектов - это конкретно List с типом Dish
`val listOfDish: List<Dish>`

2023-11-09 18:17 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_4.kt
> +    val listOfDish: List<String>,
Не строка, а объект

2023-11-10 02:30 UTC, alexandrsemc commented
Как правильно: назвать блюда humburger, chee..... или dish1, dish2.....? Если правильно присваивать имя переменных по реальному названию, то как быть с: burgerWithMushroomsAndCheese. И если в меню таких названий блюд много(длинных названий)?

2023-11-10 09:05 UTC, ievetrov commented
> Как правильно: назвать блюда humburger, chee..... или dish1, dish2.....? Если правильно присваивать имя переменных по реальному названию, то как быть с: burgerWithMushroomsAndCheese. И если в меню таких названий блюд много(длинных названий)?

при разработке реально приложения скорее всего не придется вручную создавать объекты и сохранять их в переменные. наиболее частой будет ситуация, когда будешь работать со списками данных. или парсить JSON файл, который пришел с сервера и где перечислены объекты. вся эта работа с данными не подразумевает ручное создание большого количества переменных. данные будут грубо говоря обезличены.

поэтому отвечая на вопрос разницы сейчас нет, в рамках обучения индексы можно использовать для объектов. но стараться минимизировать, ну и в продакшене лучше избегать

2023-11-10 09:06 UTC, ievetrov approved these changes
все верно, отлично. закрепили концепцию работы с объектами

2023-11-10 11:35 UTC, merged