KS-19-1 the solution of the problem
alexandrsemc/KotlinS pull request #64
Opened 2023-11-26 18:59 UTC by alexandrsemc

2023-11-27 08:21 UTC, ievetrov requested changes

2023-11-27 08:21 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_1.kt
> +    println("Вы можете добавить в свой аквариум: $fish")
Для получения списка значений enum класса в список, у этого класса есть специальный метод. Предлагаю воспользоваться им для вывода списка значений.

2023-11-28 15:58 UTC, ievetrov requested changes

2023-11-28 15:58 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_1.kt
> +    for (fish in Fish.values()) {
обрати внимание на подсказку в коде
'Enum.values()' is recommended to be replaced by 'Enum.entries' since 1.9

2023-11-28 18:33 UTC, alexandrsemc commented
В начале ничего не получалось, потом что-то обновилось, загрузилось...не знаю правильно или нет, но ошибка при использовании (entries) ушла.

2023-11-29 02:16 UTC, ievetrov approved these changes
В целом, решение корректное. Правда я писал не про **поле**, а про **метод**.
Ранее использовался (и сейчас используется, но не рекомендуется) метод values().

Поле entries появилось только версии Kotlin 1.9.0: https://kotlinlang.org/docs/whatsnew19.html#stable-replacement-of-the-enum-class-values-function

2023-11-29 02:22 UTC, merged