KS-19-2 the solution of the problem
alexandrsemc/KotlinS pull request #65
Opened 2023-11-26 19:03 UTC by alexandrsemc

2023-11-27 08:34 UTC, ievetrov requested changes

2023-11-27 08:34 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_2.kt
> +private fun setCategory(category: Category) {
Внимательнее по ТЗ - метод принимает и возвращает значение. Исключительно инкапсулированное действие

2023-11-28 16:17 UTC, ievetrov requested changes

2023-11-28 16:17 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_2.kt
> +        Category.CLOTH -> println("Одежда")
Инкапсулированное действие - имеется в виду, что во внешний мир ничего не печатается. Этот метод и должен возвращать текст расшифрованного человеческого названия. а сейчас мимо кассы печатаем, а возвращаем совсем другое) выглядит как костыль

а еще when можно сразу писать после возвращаемого типа, он умеет возвращать результат своего ветвления

2023-11-28 16:17 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_2.kt
> +fun setCategory(category: Category) :String{
форматирование (пробелы)

2023-11-28 19:09 UTC, alexandrsemc commented
Не знаю верно или нет, но вывод информации о товаре стал лучше.

2023-11-29 07:57 UTC, ievetrov approved these changes
да) теперь функция корректно возвращает строку

2023-11-29 18:36 UTC, merged