KS-3-5 the solution of the problem
alexandrsemc/KotlinS pull request #9
Opened 2023-10-03 19:17 UTC by alexandrsemc

2023-10-04 06:36 UTC, ievetrov requested changes

2023-10-04 06:36 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_5.kt
> +    val from = "D2"
ну здесь ты уже в уме выяснил и присвоил эти строки) 
сплит - верное решение! но надо докрутить,  чтобы с его помощью доставать эти элементы строки

2023-10-05 22:24 UTC, ievetrov requested changes

2023-10-05 22:24 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_5.kt
> +    val from = "D2"
println(moveSplit) не подходит.
требуется инициализировать from и др. переменные в коде. а не в уме)

посмотри какой тип возвращает сплит. это поможет определить способ вытаскивания элементов

2023-10-06 21:45 UTC, ievetrov requested changes

2023-10-06 21:45 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_5.kt
> +    (move.split("-", ";"))
попробуй сохранить в переменную результат выполнения `move.split("-", ";")`, затем принудительно вывести ее тип. это будет список (можно подробнее изучить сигнатуру метода и увидеть возвращаемое значение).

далее надо из списка по определенным индексам элементов доставать значения и присваивать переменным from итд. 

если что задача 5 - повышенной сложности, поэтому не по уровню урока. ничего страшного, если решишь вернуться к ней потом)

2023-10-07 05:15 UTC, alexandrsemc commented on src/main/kotlin/lesson_3/lesson_3_task_5.kt
> +    (move.split("-", ";"))
Понял, спасибо)

2023-11-11 08:51 UTC, ievetrov approved these changes
отлично!

2023-11-12 17:42 UTC, merged